package org.tavall.ai.staging;

public enum StagingBaseReason {
    EXPLICIT_DEPENDENCY,
    PRESERVE_EXISTING_FEATURE_PARENT,
    PRESERVE_EXISTING_STAGING_PARENT,
    EXACT_STAGING_BRANCH,
    UNIQUE_STAGING_TYPE,
    UNIQUE_REPOSITORY_STAGING,
    AMBIGUOUS_STAGING,
    NO_STAGING_FOUND
}
